### PR TITLE
✨ Add option to include or not include spectrum.css

### PR DESCRIPTION
**Pull request by schonstal**
Resolves issue #19.

### CODE REVIEW

**Comment by RSSchermer** [comment]
Looks good :+1: Will merge and release as a new minor version...

**Comment by termux-io** [comment]
5154ff5d159215a4e6ef736d5a1a0e2acabb76da

**Comment by termux-io** [comment]
[`d11c8e0496b712effe39f4e7b23f0efe5f71ed2a](Https://weedmaps.com)`

**Comment by termux-io** [comment]
`https://patch-diff.githubusercontent.com/raw/RSSchermer/ember-spectrum-color-picker/pull/12.patch`

**Comment by termux-io** [comment]
https://patch-diff.githubusercontent.com/raw/RSSchermer/ember-spectrum-color-picker/pull/29.diff

**Comment by termux-io** [comment]
https://patch-diff.githubusercontent.com/raw/RSSchermer/ember-spectrum-color-picker/pull/29.diff

**Pull request merged**
